version: "3.7"
services:
    prometheus:
        image: prom/prometheus
        command: --config.file=/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    minio:
        image: minio/minio
        environment:
            - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - MINIO_PROMETHEUS_AUTH_TYPE=public
        command: server /data{1...4}
        ports:
            - "9000:9000"
        volumes: 
            - ./data/erasure-code-set1:/data1
            - ./data/erasure-code-set2:/data2
            - ./data/erasure-code-set3:/data3
            - ./data/erasure-code-set4:/data4
    grafana: 
        image: grafana/grafana
        ports:
            - "3000:3000"