global:
    scrape_interval: 2s
    evaluation_interval: 2s
  
scrape_configs:
  - job_name: minio-job
    metrics_path: /minio/prometheus/metrics
    scheme: http
    static_configs:
        - targets: ['minio:9000']